import pygame
import sys
from pathlib import Path

pygame.init()

BASE_DIR = Path(__file__).parent.parent
ASSETS_DIR = BASE_DIR / "assets"
HB_DIR = ASSETS_DIR / "hb"
BG_DIR = ASSETS_DIR / "bg"
ON_BG_DIR = ASSETS_DIR / "on_bg"
SKINS_DIR = ASSETS_DIR / "skins"
PR_DIR = SKINS_DIR / "player"
JSON_DIR = BASE_DIR / "json"
SCREENSHOTS_DIR = BASE_DIR / "screenshots"

SCREEN_WIDTH, SCREEN_HEIGHT = 1920, 1080
FPS = 60

PLAYER_SIZE = 60

PLAYER_SPEED = 500
RUN_SPEED_MULTIPLIER = 1.8
GRAVITY = 2000
PLAYER_JUMP_POWER = -600

STAMINA_MAX = 100
STAMINA_DRAIN_RATE = 100
STAMINA_REGEN_RATE = 50

FALL_DAMAGE_THRESHOLD = 500
FALL_DAMAGE_FACTOR = 0.002

COYOTE_TIME_SECONDS = 0.1
WALL_JUMP_COOLDOWN = 0.2
MAX_CLIMB = 10